<?php 
if (!empty($block->getConfig('poptin_settings/poptin/poptin_client_id'))) :
    $client_id = $block->getConfig('poptin_settings/poptin/poptin_client_id');
    $embedType = $block->getConfig('poptin_settings/poptin/poptin_etype');

    $poptin_etype_arr = [
        "1" => "<script id='pixel-script-poptin' src='https://cdn.popt.in/pixel.js?id=" . $block->escapeJsQuote($client_id) . "' async='true'></script>\n",
        "2" => "<script>var poptinAfterPageLoad = true;</script>\n" .
               "<script id='pixel-script-poptin' src='https://cdn.popt.in/pixel.js?id=" . $block->escapeJsQuote($client_id) . "' async='true'></script>\n",
        "3" => "<script>var poptinAfterPageLoad = 'noConflict';</script>\n" .
               "<script id='pixel-script-poptin' src='https://cdn.popt.in/pixel.js?id=" . $block->escapeJsQuote($client_id) . "' async='true'></script>\n",
    ];
?>
<?= $block->escapeHtml($poptin_etype_arr[$embedType] ?? '') ?>
<?php endif; ?>